In this We will read about following:

    -arange
    -linspace
    -logspace
    -gemospace

## numpy.arange

np.arange([start],stop,[step],dtype=None)

Return evenly spaced values within a given interval.
when usin a non integer step,such as 0.1, the result  will often not be consistent. it is better to use linspace for these cases.

Parameters:

start:number,optional:Start of interval.The interval includes this value. The default start value is 0.

stop:number: end point of array.The interval does not include this value,except in some cases where step is not an integerand floating point round off affects the length of out.

step:number,optional: defines the difference between two consecutive elements of the array.Default size is 1.If step is specified as a position, start must also be given.

In [2]:
import numpy as np

In [3]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
np.arange(9.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [5]:
np.arange(0,7,1.0)

array([0., 1., 2., 3., 4., 5., 6.])

## numpy.linspace
np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)

Returns evenly spaced numbes over a specified interval.

The endpoint of the interval can optionally be excluded.

Parameters:

start:scalar: The starting value of the sequence.

stop:scalar: The end value of the sequence,unless endpoint is set to False.In that case, the sequence consists of all but the last of num+1 evenly spaced samples,so that stop is excluded. Note that the step size changes ehen the endpoint is False.

num:int,optional:Number of samples to generate.Default is 50.Must be non negatve.

endpoint: bool, optional: If true,stop is the last sample.Otherwise, it is not included. Default is True.

retsep:bool,optional:If True,return(samples,step),where step is the spacing betweeen samples.

dtype:dtype,optional: The type of output array.If dtype is not given infer the data type from the other input argument.

In [6]:
np.linspace(2,30,90)

array([ 2.        ,  2.31460674,  2.62921348,  2.94382022,  3.25842697,
        3.57303371,  3.88764045,  4.20224719,  4.51685393,  4.83146067,
        5.14606742,  5.46067416,  5.7752809 ,  6.08988764,  6.40449438,
        6.71910112,  7.03370787,  7.34831461,  7.66292135,  7.97752809,
        8.29213483,  8.60674157,  8.92134831,  9.23595506,  9.5505618 ,
        9.86516854, 10.17977528, 10.49438202, 10.80898876, 11.12359551,
       11.43820225, 11.75280899, 12.06741573, 12.38202247, 12.69662921,
       13.01123596, 13.3258427 , 13.64044944, 13.95505618, 14.26966292,
       14.58426966, 14.8988764 , 15.21348315, 15.52808989, 15.84269663,
       16.15730337, 16.47191011, 16.78651685, 17.1011236 , 17.41573034,
       17.73033708, 18.04494382, 18.35955056, 18.6741573 , 18.98876404,
       19.30337079, 19.61797753, 19.93258427, 20.24719101, 20.56179775,
       20.87640449, 21.19101124, 21.50561798, 21.82022472, 22.13483146,
       22.4494382 , 22.76404494, 23.07865169, 23.39325843, 23.70

In [8]:
np.linspace(2,30,9,endpoint=False)

array([ 2.        ,  5.11111111,  8.22222222, 11.33333333, 14.44444444,
       17.55555556, 20.66666667, 23.77777778, 26.88888889])

In [9]:
np.linspace(10,50,5,retstep=False)

array([10., 20., 30., 40., 50.])

In [10]:
np.linspace(10,50,5,retstep=True)

(array([10., 20., 30., 40., 50.]), 10.0)

## np.logspace

np.logspace(start,stop,num=50,endpoint=True, base=10.0,dttype=None)

Return numbers spaced evely on a log scale

In [11]:
np.logspace(2,30,90,base=10)

array([1.00000000e+02, 2.06351078e+02, 4.25807673e+02, 8.78658723e+02,
       1.81312174e+03, 3.74139626e+03, 7.72041151e+03, 1.59311524e+04,
       3.28741046e+04, 6.78360691e+04, 1.39980460e+05, 2.88851187e+05,
       5.96047539e+05, 1.22995052e+06, 2.53801615e+06, 5.23722369e+06,
       1.08070675e+07, 2.23005003e+07, 4.60173228e+07, 9.49572415e+07,
       1.95945291e+08, 4.04335220e+08, 8.34350085e+08, 1.72169039e+09,
       3.55272668e+09, 7.33108980e+09, 1.51277828e+10, 3.12163429e+10,
       6.44152600e+10, 1.32921583e+11, 2.74285120e+11, 5.65990301e+11,
       1.16792709e+12, 2.41003013e+12, 4.97312315e+12, 1.02620932e+13,
       2.11759399e+13, 4.36967803e+13, 9.01687771e+13, 1.86064243e+14,
       3.83945572e+14, 7.92275825e+14, 1.63486970e+15, 3.37357126e+15,
       6.96140065e+15, 1.43649253e+16, 2.96421781e+16, 6.11669540e+16,
       1.26218669e+17, 2.60453583e+17, 5.37448777e+17, 1.10903134e+18,
       2.28849813e+18, 4.72234056e+18, 9.74460063e+18, 2.01080884e+19,
      

## np.geomspace

np.geomspace(start,stop,num=50,endpoint=True,dtpe=None)

Return number spacedevenly on a log scale(geometric Pogression)

This is similar to logspace,but with endpoint specified directly.Each output sample is a constant multiple of the previous.


In [12]:
np.geomspace(2,30,90)

array([ 2.        ,  2.06179036,  2.12548974,  2.19115712,  2.25885332,
        2.32864099,  2.40058477,  2.47475127,  2.55120915,  2.63002921,
        2.71128444,  2.79505005,  2.88140362,  2.9704251 ,  3.06219692,
        3.15680404,  3.25433406,  3.3548773 ,  3.45852683,  3.56537863,
        3.67553165,  3.78908785,  3.9061524 ,  4.02683368,  4.15124342,
        4.27949683,  4.41171265,  4.5480133 ,  4.68852498,  4.8333778 ,
        4.98270587,  5.13664746,  5.2953451 ,  5.45894573,  5.62760084,
        5.80146657,  5.98070392,  6.16547883,  6.35596241,  6.552331  ,
        6.75476644,  6.96345615,  7.17859338,  7.4003773 ,  7.62901328,
        7.86471301,  8.10769472,  8.3581834 ,  8.61641097,  8.88261653,
        9.15704655,  9.43995514,  9.73160424, 10.0322639 , 10.34221248,
       10.66173699, 10.99113326, 11.33070628, 11.68077048, 12.04164997,
       12.4136789 , 12.79720173, 13.19257356, 13.60016048, 14.02033987,
       14.45350077, 14.90004426, 15.36038379, 15.8349456 , 16.32

In [13]:
np.geomspace(1,1000,4)

array([   1.,   10.,  100., 1000.])