# This is Practice For Numpy module


# Methods of Creation of Numpy array

In [1]:
#Import the numpy module
import numpy as np

### 1.) np.array()

In [3]:
#in parameter we have to give sequence of elements
a=np.array([2,3])
print(a)
print('shape of array a is :',a.shape)

[2 3]
shape of array a is : (2,)


In [6]:
# Now we will make 2-d array
a=np.array([[1,2,3],[4,5,6]])
print("Two dimensional array is:",a)
print("Shape of array is :",a.shape)

Two dimensional array is: [[1 2 3]
 [4 5 6]]
Shape of array is : (2, 3)


### 2.) np.empty(shape,dtype=float,order='C')

In [11]:
a=np.empty((2,3),dtype=int,order='C')
print("array of order (2,3) is : \n",a)
#Random values will present n array generated by empty method.

array of order (2,3) is : 
 [[              1  93852441767184  93849330384924]
 [140536262599544 140535624892418 140535624892418]]


In [12]:
print(np.empty(([2,3],dtype=str)))
#try to change dtype argument of empty

SyntaxError: invalid syntax (<ipython-input-12-72dd9f8dc8e9>, line 1)

In [15]:
a=np.empty([2,3],dtype=float,order='C')
print(a)
print(a.shape)

[[4.94065646e-324 4.63692673e-310 4.63677300e-310]
 [6.94341393e-310 6.94338243e-310 6.94338243e-310]]
(2, 3)


### 3.) np.empty_like(array_like,dtype=None,order='K',subok=True)

#Return a new array with same shape and type as a given array.
array_like:a:The shape and data-type of a define these same attrbute of returne array
dtype:optional parameter and Override the data type of result.
oder:{'C','F','A',or 'K'} it is also optional.Override the memory layout of result.
    'C' means C-order
    'F' means F-order
    'A' means 'F' if a Fortran contiguous,'C' otherwise
    'K' means match the layout of array_like as closely as possible.
subok:
    bool,optional:
    If True,then newly created array will use the sub-class type of 'a',otherwise it wil be a base-class array.Defaults to True.
    

In [18]:
a=[[1,2,3],[4,5,6]]
b=np.empty_like(a)
print('empty_like array(b) is: {}\nSimple array(a) is {}'.format(b,a))

empty_like array(b) is: [[              1  93852441767184  93849330384924]
 [140536262599544 140535624892418 140535624892418]]
Simple array(a) is [[1, 2, 3], [4, 5, 6]]


In [19]:
print('Shape of b and type of b is:',b.shape,type(b))

Shape of b and type of b is: (2, 3) <class 'numpy.ndarray'>


In [20]:
print('Shape of a and type of a is:',a.shape,type(a))

AttributeError: 'list' object has no attribute 'shape'

In [21]:
print(type(a),' due to this data type error raise in previous part')

<class 'list'>  due to this data type error raise in previous part


### 4.)np.eye(N,M=None,k=0,dtype=<class 'float'>,order='C')

Parameter :
N:Number of rows in output

M:int,optional:Number of columns in the output.If None ,defaults to N.

k:int,optioal:Index of diagonal :0(the default)refers to the main diagonal,a positive value refers to an upper diagonal, and negative value to a lower diagonal.

In [22]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [23]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [24]:
np.eye(3,2,k=-1)

array([[0., 0.],
       [1., 0.],
       [0., 1.]])

In [25]:
np.eye(3,2,k=0)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

### 5.)np.identity(n,dtype=None)

Return the identity array : The identity array is a square array with ones on the main diagonal.

Parameter :

n:int:Number of rows(and columns ) in n*n outpt


dtype:Default to float.

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 6.)np.ones(shape,dtype=None,order='C')

Returns a new array of given shape and type ,filled with ones.
Parameters:

shape:int or sequence of ints:Shape of new array, e.g.,(2,3) or 2.

dtpe:data-type, optional : the desired data-type for the array. eg- numpy.int8.Default to numpy.float64.

In [29]:
print(np.ones(2))
print(np.ones(2).shape)

[1. 1.]
(2,)


### 7.)np.ones_like(a,dtype=None,order='K',subok=True)

Return an array of oness with the same shape and type as a given array.

Paramters:

a:array_like:The shape and data type of a define these same attribute of returned array.


In [30]:
a=np.array([[1,2,3],[5,6,7]])

In [31]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

### 8.)np.zeros(shape,dtype=float,order='C')

return a new array of given shape and type, filled with zeros

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros(2,2)

TypeError: data type not understood

In [36]:
#In the complex data type is used.
np.zeros((3,),dtype=[('x','i4'),('y','i4')])

array([(0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

### 9.) np.full(shape,fill_value,dtype=None,order='C')

return a new array of given shape and type, filled with fll_value.

Parameters:

shape:int or sequence of ints: Shape of new array. e.g.(2,3) or 2.

fil_value:scalar:Fill value.

In [37]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [38]:
np.full((2,2),np.inf)

array([[inf, inf],
       [inf, inf]])

### 10.) np.full_like(a, fill_value,dtype=None,order='K',subok=True)

Returns a full array with same shape and type s a given array.

Parameters:

a:array_like:The shape and data-type of a define these same attributes of returned array.

fill_value:scalar: Fill value.

dtype:data-type, optional: Overrides the data type of the result.

In [39]:
x=np.arange(6,dtype=int)
np.full_like(x,1)

array([1, 1, 1, 1, 1, 1])

In [41]:
#Now in this we will passing fill_ value of float type but the answer will be of int type this is because we do not explicitly mention the data type. So it inherit the data type of x which is int hence the answer comes in int type.
np.full_like(x,3.4)

array([3, 3, 3, 3, 3, 3])