## Broadcasting

Ability of numpy to treat arrays of different shapes during arithmetic operations.

Arithmetic operations on arrays are usually done on corresponing elements.If two arrays are of exactly the same shape,then these operations are smoothy performed.

In [1]:
import numpy as np

In [12]:
a=np.array([[1,2],[3,4]])
b=np.array([1])
print('a:',a)
print('b:',b)

a: [[1 2]
 [3 4]]
b: [1]


In [13]:
a+b

array([[2, 3],
       [4, 5]])

In [42]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.arange(4).reshape((1,4))

In [43]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
b

array([[0, 1, 2, 3]])

In [45]:
a+b

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11]])

In [46]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
b

array([[0, 1, 2, 3]])

In [48]:
np.add(a,b)

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11]])

In [49]:
np.subtract(a,b)

array([[1, 1, 1, 1],
       [5, 5, 5, 5]])

In [51]:
np.multiply(a,b)

array([[ 0,  2,  6, 12],
       [ 0,  6, 14, 24]])

In [52]:
c=np.divide(b,a)

In [53]:
c

array([[0.        , 0.5       , 0.66666667, 0.75      ],
       [0.        , 0.16666667, 0.28571429, 0.375     ]])

In [54]:
np.around(c)

array([[0., 0., 1., 1.],
       [0., 0., 0., 0.]])

In [57]:
np.around(c,decimals=-1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.around(c,decimals=1)

array([[0. , 0.5, 0.7, 0.8],
       [0. , 0.2, 0.3, 0.4]])

## Floor

np.floor()

this function returns the largest integer not greater than the input parameter. the floor of the scaler x is the largest integer i,such that i<=x.

Note that in python flooring always rounding away from zero.

In [60]:
a=np.array([-1.2,3.2,4.7,-0.2,0.2,7])

In [61]:
np.floor(a)

array([-2.,  3.,  4., -1.,  0.,  7.])

## np.dot(arry1,arry2)

This function returns the dot product of two arrays.

For Ndimensional arrays, it is sum product over the last axis of a and the second-last axis of b.

In [83]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [84]:
b=np.arange(10,18).reshape(2,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [71]:
np.dot(a,b)

array([[ 38,  41,  44,  47],
       [ 86,  93, 100, 107]])

In [72]:
np.dot(b,a)

ValueError: shapes (2,4) and (2,2) not aligned: 4 (dim 1) != 2 (dim 0)

## np.vdot(vectr1,vectr2)

This function returns the dot product of two vectors for 1-D arrays.

For higher dimensions, it reutrns the sum product over the last axis.

In [73]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])

In [74]:
a

array([[1, 2],
       [3, 4]])

In [75]:
b

array([[11, 12],
       [13, 14]])

In [76]:
np.vdot(a,b)

130

In [78]:
np.vdot(b,a)

130

## MAtrix multiplication

np.matmul()

This funcion returns the marix product of two arrays.

In [80]:
a

array([[1, 2],
       [3, 4]])

In [81]:
b

array([[11, 12],
       [13, 14]])

In [82]:
np.matmul(a,b)

array([[37, 40],
       [85, 92]])

## np.linalg.det()

Deteminant is very usueful value in the linear algebra. It calculated from the diagonal elements of a square matrix. For a 2*2 matrix,it is simply the subtraction of product of the top left and bottom right element from the product of other two.

## linalg.inv()

we use this function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix,it reutns in identity matrix.

In [86]:
a

array([[1, 2],
       [3, 4]])

In [87]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])